Vagrant.configure "2" do |config|

  config.vm.box = "vagrant-hackaton"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.cache.auto_detect = false
  config.cache.scope = :box

  config.vm.network :forwarded_port, guest: 80, host: 2080
  # TODO3 add port mappings from 8080 and 8443 to same ports at host 
 
  config.vm.synced_folder "webapp/", "/var/www/html"

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"   
    # TODO2 add cookbooks for Java and Tomcat 
    chef.add_recipe "my_webserver"
    chef.add_recipe "my_webserver::tomcat_proxy"
  end

end