Vagrant.configure "2" do |config|

  config.vm.box = "vagrant-hackaton"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.cache.auto_detect = false
  config.cache.scope = :box

  #TODO 2 add mapping for 3306 port (might be needed for connection from host machine)

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"   
    chef.add_recipe "mysql::client"
    chef.add_recipe "mysql::server"

    chef.json = {
       "mysql" => {
         "server_root_password" => "secret"
       }
     }
  end

end